const url: string = 'https://kenneth-andales/portfolio/images'

export const workOne: string[] = [
  `${url}/work1/1.png`,
  `${url}/work1/2.png`,
  `${url}/work1/3.png`,
  `${url}/work1/4.png`,
  `${url}/work1/5.png`,
  `${url}/work1/6.png`,
  `${url}/work1/7.png`,
  `${url}/work1/8.png`,
  `${url}/work1/9.png`,
  `${url}/work1/10.png`,
  `${url}/work1/11.png`,
  `${url}/work1/12.png`,
  `${url}/work1/13.png`,
  `${url}/work1/14.png`,
  `${url}/work1/15.png`,
  `${url}/work1/16.png`,
  `${url}/work1/17.png`,
  `${url}/work1/18.png`,
  `${url}/work1/19.png`,
  `${url}/work1/20.png`,
  `${url}/work1/21.png`,
  `${url}/work1/22.png`,
  `${url}/work1/23.png`,
  `${url}/work1/24.png`,
  `${url}/work1/25.png`,
  `${url}/work1/26.png`,
  `${url}/work1/27.png`,
  `${url}/work1/28.png`,
  `${url}/work1/29.png`,
]

export const workTwo = [
  `${url}/work2/1.png`,
  `${url}/work2/2.png`,
  `${url}/work2/3.png`,
  `${url}/work2/4.png`,
  `${url}/work2/5.png`,
  `${url}/work2/6.png`,
  `${url}/work2/7.png`,
  `${url}/work2/8.png`,
  `${url}/work2/9.png`,
  `${url}/work2/10.png`,
  `${url}/work2/11.png`,
  `${url}/work2/12.png`,
  `${url}/work2/13.png`,
  `${url}/work2/error.png`,
]

export const workThree = [
  `${url}/work3/1.png`,
  `${url}/work3/2.png`,
  `${url}/work3/3.png`,
  `${url}/work3/4.png`,
  `${url}/work3/5.png`,
  `${url}/work3/6.png`,
  `${url}/work3/7.png`,
  `${url}/work3/8.png`,
  `${url}/work3/9.png`,
]

export const workFour = [
  `${url}/work4/1.png`,
  `${url}/work4/2.png`,
  `${url}/work4/3.png`,
  `${url}/work4/4.png`,
  `${url}/work4/5.png`,
  `${url}/work4/6.png`,
  `${url}/work4/7.png`,
  `${url}/work4/8.png`,
  `${url}/work4/9.png`,
  `${url}/work4/10.png`,
  `${url}/work4/11.png`,
]

export const workFive = [
  `${url}/work7/1.png`,
  `${url}/work7/2.png`,
  `${url}/work5/3.png`,
  `${url}/work5/4.png`,
  `${url}/work5/5.png`,
  `${url}/work5/6.png`,
  `${url}/work5/7.png`,
  `${url}/work5/8.png`,
  `${url}/work5/9.png`,
  `${url}/work5/10.png`,
  `${url}/work5/11.png`,
  `${url}/work5/12.png`,
  `${url}/work5/13.png`,
  `${url}/work5/14.png`,
  `${url}/work5/15.png`,
  `${url}/work5/16.png`,
  `${url}/work5/17.png`,
  `${url}/work5/18.png`,
  `${url}/work5/19.png`,
  `${url}/work5/20.png`,
  `${url}/work5/21.png`,
  `${url}/work5/22.png`,
]

export const workSix = [
  `${url}/work6/1.png`,
  `${url}/work6/2.png`,
  `${url}/work6/3.png`,
  `${url}/work6/4.png`,
  `${url}/work6/5.png`,
  `${url}/work6/6.png`,
  `${url}/work6/7.png`,
  `${url}/work6/8.png`,
  `${url}/work6/9.png`,
  `${url}/work6/10.png`,
  `${url}/work6/11.png`,
  `${url}/work6/12.png`,
  `${url}/work6/13.png`,
  `${url}/work6/14.png`,
]

export const workSeven = [
  `${url}/work7w/1.png`,
  `${url}/work7/2.png`,
  `${url}/work7/3.png`,
  `${url}/work7/5.png`,
  `${url}/work7/6.png`,
  `${url}/work7/7.png`,
  `${url}/work7/8.png`,
  `${url}/work7/9.png`,
  `${url}/work7/10.png`,
  `${url}/work7/11.png`,
  `${url}/work7/12.png`,
  `${url}/work7/13.png`,
  `${url}/work7/14.png`,
  `${url}/work7/15.png`,
  `${url}/work7/16.png`,
]
